spin_manifest_version = 2

[application]
name = "delt"
version = "0.1.0"
authors = ["Altair"]
description = "Language Learning App"

[[trigger.http]]
route = "/..."
component = "delt"

[component.delt]
source = "target/generated/wasm/teavm/classes.wasm"
allowed_outbound_hosts = [ "https://raw.githubusercontent.com" ]
files = [{ source = "static-assets/", destination = "/" }]

[component.delt.build]
command = "mvn prepare-package"