spin_manifest_version = 2

[application]
name = "delt"
version = "0.1.0"
authors = ["Altair"]
description = "PNMM Buddies"

[[trigger.http]]
route = "/..."
component = "delt"

[component.delt]
source = "target/generated/wasm/teavm/classes.wasm"

[component.delt.build]
command = "mvn clean package"